const $=s=>document.querySelector(s);let items=[],active='all',previewed=new Set(),topicText='',searchButton=null;
$('#search').onclick=async()=>{const b=$('#search'),script=$('#script').value.trim();if(!script)return alert('대본을 입력하세요.');searchButton=b;b.disabled=true;b.textContent='검색 준비 중…';$('#results').innerHTML='<div class="empty">전 세계 숏폼 결과를 합쳐 10개 찾고 있습니다.</div>';$('#status').textContent='다국어 검색 준비 중';try{const r=await fetch('/api/discover',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({script,per_platform:10})});const text=await r.text();let d;try{d=JSON.parse(text)}catch{throw Error('서버가 잠시 재시작 중입니다. 1분 후 다시 눌러주세요.')}if(!r.ok)throw Error(d.detail||'검색 시작 실패');pollDiscovery(d.job_id)}catch(e){showError(e.message)}};
async function pollDiscovery(id){try{const r=await fetch('/api/jobs/'+id),text=await r.text();let d;try{d=JSON.parse(text)}catch{throw Error('서버 응답이 지연되고 있습니다. 잠시 후 다시 시도하세요.')}if(!r.ok)throw Error(d.detail||'진행 상태 확인 실패');$('#status').textContent=d.message||'검색 중';if(d.status==='done'){finishSearch(d.data);return}if(d.status==='error'){throw Error(d.message||'검색 실패')}setTimeout(()=>pollDiscovery(id),1800)}catch(e){showError(e.message)}}
function finishSearch(d){items=d.results||[];active='all';topicText=d.topic||'';filters(d.translations||[]);draw();const c=countByPlatform();$('#status').textContent=`총 ${items.length}개 · YouTube ${c.youtube||0} · TikTok ${c.tiktok||0} · Reels ${c.instagram||0} · 샤오홍슈 ${c.xiaohongshu||0}`;searchButton.disabled=false;searchButton.textContent='짧은 영상 전체 검색'}
function showError(message){$('#results').innerHTML=`<div class="empty">${esc(message)}</div>`;$('#status').textContent='검색 실패';if(searchButton){searchButton.disabled=false;searchButton.textContent='짧은 영상 전체 검색'}}
function countByPlatform(){return items.reduce((a,x)=>(a[x.platform]=(a[x.platform]||0)+1,a),{})}
function filters(translations){const names=[['all','전체'],['youtube','YouTube'],['tiktok','TikTok'],['instagram','Reels'],['xiaohongshu','샤오홍슈']],langs=translations.map(x=>x.query).join(' · ');$('#summary').innerHTML=`<p class="note">다국어 검색어: ${esc(langs||topicText)}</p>`+names.map(([k,n])=>`<button class="chip ${active===k?'on':''}" data-p="${k}">${n} ${k==='all'?items.length:items.filter(x=>x.platform===k).length}</button>`).join('');document.querySelectorAll('.chip').forEach(x=>x.onclick=()=>{active=x.dataset.p;filters(translations);draw()})}
function draw(){const list=active==='all'?items:items.filter(x=>x.platform===active);if(!list.length){$('#results').innerHTML='<div class="empty">이 플랫폼에서 찾은 영상이 없습니다.</div>';return}$('#results').innerHTML=list.map(v=>`<article class="scene result" data-url="${attr(v.url)}" data-platform="${v.platform}" data-id="${attr(v.id||'')}" data-title="${attr(v.title)}"><div class="badge">${esc(v.platform_label)} · ${esc((v.language||'').toUpperCase())}</div>${v.thumbnail?`<img src="${attr(v.thumbnail)}" loading="lazy">`:''}<div class="sentence">${esc(v.title)}</div><div class="query">${v.duration?`${Math.round(v.duration)}초 · `:''}자막 없음 가능성 높음</div><button class="view">미리보기 추가</button><a href="${attr(v.url)}" target="_blank" rel="noopener" class="note">원본 열기</a></article>`).join('');document.querySelectorAll('.result').forEach(card=>card.querySelector('.view').onclick=()=>addPreview(card.dataset.url,card.dataset.platform,card.dataset.id,card.dataset.title))}
function addPreview(url,platform,id,title){if(previewed.has(url))return;previewed.add(url);const box=$('#previews');if(box.querySelector('.empty'))box.innerHTML='';let src='';if(platform==='youtube'&&id)src=`https://www.youtube.com/embed/${id}?playsinline=1`;else if(platform==='tiktok'){const m=url.match(/video\/(\d+)/);if(m)src=`https://www.tiktok.com/player/v1/${m[1]}`}else if(platform==='instagram')src=url.replace(/\/$/,'')+'/embed';const card=document.createElement('article');card.className='scene';card.style.marginBottom='14px';card.innerHTML=`<div class="sentence">${esc(title)}</div>${src?`<iframe src="${attr(src)}" allow="autoplay; encrypted-media; picture-in-picture" allowfullscreen style="width:100%;aspect-ratio:9/16;max-height:520px;border:0;border-radius:12px;background:#000"></iframe>`:`<div class="empty">이 플랫폼은 원본 게시물에서 재생하세요.</div>`}<a href="${attr(url)}" target="_blank" rel="noopener" style="display:block;background:#65e6b3;color:#07100d;padding:12px;border-radius:10px;text-align:center;font-weight:800;text-decoration:none">원본 게시물 열기</a>`;box.appendChild(card);$('#status').textContent=`미리보기 ${previewed.size}개 추가됨`}
function esc(s){return String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function attr(s){return esc(s)}
